import { Company } from '../models/types';

export const companies: Company[] = [
  {
    id: 'amzn',
    ticker: 'AMZN',
    name: 'Amazon',
    logo: '/assets/kenney_ui-pack/PNG/green_button09.png', // Will replace with appropriate logo
    description: 'Amazon.com, Inc. is an American multinational technology company focusing on e-commerce, cloud computing, online advertising, digital streaming, and artificial intelligence. It has been referred to as "one of the most influential economic and cultural forces in the world" and is one of the world\'s most valuable brands. It is one of the Big Five American information technology companies, alongside Alphabet, Apple, Meta, and Microsoft.\n\nAmazon was founded by Jeff Bezos from his garage in Bellevue, Washington, on July 5, 1994. Initially an online marketplace for books, it has expanded into a multitude of product categories including electronics, fashion, furniture, food, toys, and more. Amazon has multiple subsidiaries including Amazon Web Services (cloud computing), Zoox (autonomous vehicles), Kuiper Systems (satellite internet), and Amazon Lab126 (computer hardware R&D).',
    sector: 'Consumer Cyclical',
    industry: 'Internet Retail',
    website: 'https://www.amazon.com',
    financials: {
      revenue: '$574.8 billion',
      profit: '$30.4 billion',
      growthRate: '11.9%',
      peRatio: '41.2',
      marketCap: '$1.83 trillion',
      dividendYield: 'N/A',
    },
    news: [
      {
        id: 'amzn-news-1',
        date: '2024-02-28',
        headline: 'Amazon to Add More Generative AI Features to AWS',
        summary: 'Amazon announced new generative AI capabilities for its Amazon Web Services cloud division, aiming to compete with Microsoft and Google in the rapidly expanding AI market.',
        impact: 'positive',
      },
      {
        id: 'amzn-news-2',
        date: '2024-02-15',
        headline: 'Amazon Expands Same-Day Delivery to More Cities',
        summary: 'Amazon has expanded its same-day delivery service to 15 additional metropolitan areas, strengthening its logistics advantage over traditional retailers.',
        impact: 'positive',
      },
      {
        id: 'amzn-news-3',
        date: '2024-02-01',
        headline: 'Amazon Reports Strong Q4 Earnings',
        summary: 'Amazon exceeded Wall Street expectations with Q4 earnings showing 14% revenue growth and stronger-than-expected performance from AWS despite cloud spending concerns.',
        impact: 'positive',
      },
      {
        id: 'amzn-news-4',
        date: '2024-01-15',
        headline: 'Amazon to Cut Over 18,000 Jobs',
        summary: 'Amazon announced it will lay off more than 18,000 employees, primarily in its retail and human resources divisions, as part of cost-cutting measures.',
        impact: 'neutral',
      },
    ],
    documents: [
      {
        id: 'amzn-doc-1',
        title: 'Amazon Annual Report 2023',
        type: 'pdf',
        description: 'Comprehensive financial statements and business overview for fiscal year 2023.',
      },
      {
        id: 'amzn-doc-2',
        title: 'Amazon Web Services: Strategic Analysis',
        type: 'presentation',
        description: 'Analysis of AWS market position, growth trajectory, and competitive landscape.',
      },
      {
        id: 'amzn-doc-3',
        title: 'Amazon E-commerce Market Share Data',
        type: 'spreadsheet',
        description: 'Detailed breakdown of Amazon\'s market share across different product categories and regions.',
      },
    ],
  },
  {
    id: 'nvda',
    ticker: 'NVDA',
    name: 'NVIDIA',
    logo: '/assets/kenney_ui-pack/PNG/green_button09.png',
    description: 'NVIDIA Corporation is an American multinational technology company designing graphics processing units (GPUs) for the gaming and professional markets, as well as system-on-chip units for the mobile computing and automotive markets. Based in Santa Clara, California, its primary GPU line is labeled "GeForce" for gaming and "RTX" for AI and ray-tracing applications.\n\nFounded in 1993 by Jensen Huang, Chris Malachowsky, and Curtis Priem, NVIDIA initially focused on manufacturing GPUs for gaming and multimedia. The company has since expanded into various markets including professional visualization, data centers, and artificial intelligence. NVIDIA has become a leading player in the AI field, with its GPUs being widely used for deep learning and other AI applications.',
    sector: 'Technology',
    industry: 'Semiconductors',
    website: 'https://www.nvidia.com',
    financials: {
      revenue: '$60.9 billion',
      profit: '$29.8 billion',
      growthRate: '126%',
      peRatio: '74.5',
      marketCap: '$2.2 trillion',
      dividendYield: '0.03%',
    },
    news: [
      {
        id: 'nvda-news-1',
        date: '2024-03-01',
        headline: 'NVIDIA Unveils Next-Generation AI Chips',
        summary: 'NVIDIA announced its next-generation AI chips promising 4x performance increases over current models, reinforcing its leadership in the AI hardware market.',
        impact: 'positive',
      },
      {
        id: 'nvda-news-2',
        date: '2024-02-21',
        headline: 'NVIDIA Reports Record Q4 Revenue',
        summary: 'NVIDIA shattered Wall Street expectations with record quarterly revenue of $22.1 billion, up 265% year-over-year, driven by surging demand for AI chips.',
        impact: 'positive',
      },
      {
        id: 'nvda-news-3',
        date: '2024-02-10',
        headline: 'NVIDIA Partners with Major Cloud Providers',
        summary: 'NVIDIA announced expanded partnerships with AWS, Google Cloud, and Microsoft Azure to deploy its new AI chips across these cloud platforms.',
        impact: 'positive',
      },
      {
        id: 'nvda-news-4',
        date: '2024-01-25',
        headline: 'Competitors Challenge NVIDIA\'s AI Chip Dominance',
        summary: 'AMD and Intel unveiled new AI accelerators aimed at competing with NVIDIA\'s market-leading GPUs, potentially threatening NVIDIA\'s dominant position.',
        impact: 'negative',
      },
    ],
    documents: [
      {
        id: 'nvda-doc-1',
        title: 'NVIDIA Annual Report 2023',
        type: 'pdf',
        description: 'Comprehensive financial statements and business overview for fiscal year 2023.',
      },
      {
        id: 'nvda-doc-2',
        title: 'NVIDIA AI Computing Strategy',
        type: 'presentation',
        description: 'Overview of NVIDIA\'s strategic positioning in the AI computing market and future roadmap.',
      },
      {
        id: 'nvda-doc-3',
        title: 'GPU Market Share Analysis',
        type: 'spreadsheet',
        description: 'Detailed breakdown of GPU market share across gaming, professional, and AI segments.',
      },
    ],
  },
  {
    id: 'mu',
    ticker: 'MU',
    name: 'Micron',
    logo: '/assets/kenney_ui-pack/PNG/green_button09.png',
    description: 'Micron Technology, Inc. is an American producer of computer memory and computer data storage including dynamic random-access memory (DRAM), flash memory, and USB flash drives. It is headquartered in Boise, Idaho. Its consumer products are marketed under the brands Crucial and Ballistix.\n\nFounded in 1978, Micron has grown into one of the largest memory chip manufacturers in the world. The company produces a wide range of semiconductor devices, focusing primarily on DRAM, NAND Flash, and NOR Flash memory. These technologies are used in a variety of applications including computers, mobile devices, consumer electronics, data centers, automotive, and industrial applications.',
    sector: 'Technology',
    industry: 'Semiconductors',
    website: 'https://www.micron.com',
    financials: {
      revenue: '$30.8 billion',
      profit: '$2.1 billion',
      growthRate: '15.4%',
      peRatio: '89.7',
      marketCap: '$147.8 billion',
      dividendYield: '0.41%',
    },
    news: [
      {
        id: 'mu-news-1',
        date: '2024-02-28',
        headline: 'Micron Begins Mass Production of HBM3E Memory for AI',
        summary: 'Micron announced it has started mass production of High Bandwidth Memory 3E (HBM3E), targeting the growing demand for memory in AI applications.',
        impact: 'positive',
      },
      {
        id: 'mu-news-2',
        date: '2024-02-15',
        headline: 'Micron Expands Manufacturing Capacity in United States',
        summary: 'Micron unveiled plans to invest $15 billion in a new memory chip manufacturing facility in the U.S., enhancing domestic semiconductor production.',
        impact: 'positive',
      },
      {
        id: 'mu-news-3',
        date: '2024-02-01',
        headline: 'Micron Projects Memory Chip Shortage in Second Half of 2024',
        summary: 'Micron forecasts a potential shortage of DRAM and NAND memory chips later this year as AI demand continues to grow faster than supply expansion.',
        impact: 'positive',
      },
      {
        id: 'mu-news-4',
        date: '2024-01-15',
        headline: 'Micron Reports Better-Than-Expected Quarterly Results',
        summary: 'Micron exceeded analyst expectations for its fiscal Q1 2024, with revenue up 16% year-over-year driven by strong data center demand.',
        impact: 'positive',
      },
    ],
    documents: [
      {
        id: 'mu-doc-1',
        title: 'Micron Annual Report 2023',
        type: 'pdf',
        description: 'Comprehensive financial statements and business overview for fiscal year 2023.',
      },
      {
        id: 'mu-doc-2',
        title: 'Memory Industry Outlook 2024-2026',
        type: 'presentation',
        description: 'Analysis of memory market trends and Micron\'s strategic positioning for the next three years.',
      },
      {
        id: 'mu-doc-3',
        title: 'Micron Product Roadmap',
        type: 'spreadsheet',
        description: 'Detailed information on Micron\'s upcoming memory technologies and product release schedule.',
      },
    ],
  },
  {
    id: 'wmt',
    ticker: 'WMT',
    name: 'Walmart',
    logo: '/assets/kenney_ui-pack/PNG/green_button09.png',
    description: 'Walmart Inc. is an American multinational retail corporation that operates a chain of hypermarkets, discount department stores, and grocery stores from the United States, headquartered in Bentonville, Arkansas. The company was founded by Sam Walton in 1962 and incorporated on October 31, 1969.\n\nWalmart is the world\'s largest company by revenue, with about $570 billion in annual revenue, according to the Fortune Global 500 list. It is also the largest private employer in the world with 2.3 million employees. Walmart is a family-owned business, as the company is controlled by the Walton family, who own over 50 percent of Walmart through their holding company Walton Enterprises and their individual holdings.',
    sector: 'Consumer Defensive',
    industry: 'Discount Stores',
    website: 'https://www.walmart.com',
    financials: {
      revenue: '$648.1 billion',
      profit: '$15.5 billion',
      growthRate: '6.1%',
      peRatio: '29.4',
      marketCap: '$456.7 billion',
      dividendYield: '1.41%',
    },
    news: [
      {
        id: 'wmt-news-1',
        date: '2024-02-28',
        headline: 'Walmart Expands Healthcare Services',
        summary: 'Walmart announced plans to open 28 new health centers in 2024, continuing its expansion into primary care services across multiple states.',
        impact: 'positive',
      },
      {
        id: 'wmt-news-2',
        date: '2024-02-15',
        headline: 'Walmart Reports Strong E-Commerce Growth',
        summary: 'Walmart\'s Q4 earnings showed e-commerce sales up 23% year-over-year, demonstrating continued success in digital transformation efforts.',
        impact: 'positive',
      },
      {
        id: 'wmt-news-3',
        date: '2024-02-01',
        headline: 'Walmart Raises Minimum Wage to $15 Per Hour',
        summary: 'Walmart announced it will increase its minimum wage to $15 per hour for all U.S. employees, affecting approximately 700,000 workers.',
        impact: 'neutral',
      },
      {
        id: 'wmt-news-4',
        date: '2024-01-15',
        headline: 'Walmart+ Subscription Service Reaches 18 Million Members',
        summary: 'Walmart\'s membership program has grown to 18 million subscribers, showing progress in competing with Amazon Prime for consumer loyalty.',
        impact: 'positive',
      },
    ],
    documents: [
      {
        id: 'wmt-doc-1',
        title: 'Walmart Annual Report 2023',
        type: 'pdf',
        description: 'Comprehensive financial statements and business overview for fiscal year 2023.',
      },
      {
        id: 'wmt-doc-2',
        title: 'Walmart Digital Strategy',
        type: 'presentation',
        description: 'Overview of Walmart\'s e-commerce and omnichannel retail strategy and implementation roadmap.',
      },
      {
        id: 'wmt-doc-3',
        title: 'Walmart Store Performance Analysis',
        type: 'spreadsheet',
        description: 'Data on store performance metrics across different regions and store formats.',
      },
    ],
  },
  {
    id: 'dis',
    ticker: 'DIS',
    name: 'Walt Disney',
    logo: '/assets/kenney_ui-pack/PNG/green_button09.png',
    description: 'The Walt Disney Company, commonly known as Disney, is an American multinational mass media and entertainment conglomerate headquartered at the Walt Disney Studios complex in Burbank, California. Disney was originally founded on October 16, 1923, by brothers Walt and Roy O. Disney as the Disney Brothers Cartoon Studio; it also operated under the names The Walt Disney Studio and Walt Disney Productions before changing its name to The Walt Disney Company in 1986.\n\nThe company is known for its film studio division, The Walt Disney Studios, which includes Walt Disney Pictures, Walt Disney Animation Studios, Pixar, Marvel Studios, Lucasfilm, 20th Century Studios, Searchlight Pictures, and Blue Sky Studios. Disney\'s other main business units include Disney Media & Entertainment Distribution, Disney Parks, Experiences and Products, and Disney Direct-to-Consumer & International.',
    sector: 'Communication Services',
    industry: 'Entertainment',
    website: 'https://www.thewaltdisneycompany.com',
    financials: {
      revenue: '$88.9 billion',
      profit: '$4.1 billion',
      growthRate: '7.5%',
      peRatio: '76.2',
      marketCap: '$197.4 billion',
      dividendYield: '0.75%',
    },
    news: [
      {
        id: 'dis-news-1',
        date: '2024-02-28',
        headline: 'Disney Streaming Services Reach Profitability Milestone',
        summary: 'Disney announced that its streaming division, including Disney+, Hulu, and ESPN+, achieved profitability for the first time in Q1 2024.',
        impact: 'positive',
      },
      {
        id: 'dis-news-2',
        date: '2024-02-15',
        headline: 'Disney Announces New Theme Park Expansion',
        summary: 'Disney revealed plans for a $2 billion expansion at one of its theme parks, featuring new attractions based on popular franchises.',
        impact: 'positive',
      },
      {
        id: 'dis-news-3',
        date: '2024-02-01',
        headline: 'Disney\'s Latest Film Breaks Box Office Records',
        summary: 'Disney\'s newest animated feature film surpassed $1 billion in global box office revenue, becoming the highest-grossing animated film of the year.',
        impact: 'positive',
      },
      {
        id: 'dis-news-4',
        date: '2024-01-15',
        headline: 'Disney Announces Restructuring and Cost-Cutting Measures',
        summary: 'Disney outlined plans to reduce expenses by $5.5 billion through organizational restructuring and workforce reductions across divisions.',
        impact: 'neutral',
      },
    ],
    documents: [
      {
        id: 'dis-doc-1',
        title: 'Disney Annual Report 2023',
        type: 'pdf',
        description: 'Comprehensive financial statements and business overview for fiscal year 2023.',
      },
      {
        id: 'dis-doc-2',
        title: 'Disney Streaming Strategy',
        type: 'presentation',
        description: 'Analysis of Disney\'s direct-to-consumer streaming business model and competitive positioning.',
      },
      {
        id: 'dis-doc-3',
        title: 'Disney Media Network Performance',
        type: 'spreadsheet',
        description: 'Performance metrics across Disney\'s various media networks and content distribution channels.',
      },
    ],
  },
];